#define MAX_STR_SIZE 100

#define REQUEST_CODE_LIST 1
#define REQUEST_CODE_PUT 2
#define REQUEST_CODE_GET 3
#define REQUEST_CODE_HELP 4
#define REQUEST_CODE_QUIT 5
#define REQUEST_CODE_SIZE 6

#define RESPONSE_CODE_OK 1
#define RESPONSE_CODE_NOT_IMPLEMENTED 2
#define RESPONDE_CODE_ERROR 3
#define RESPONDE_CODE_SIZE 4
